### PR TITLE
Added the ability to manually approve resumes

### LINKED ISSUE #17: Add a route to manually approve resumes
Add a route that allows officers/users with a certain permission level to manually approve resumes before they end up in the final/production resumes collection so we can verify the accuracy and quality of the information provided

Backend
 - Change it so that when resumes are first uploaded they are saved to a collection that contains all resumes that still need to be manually approved and not automatically put in the resumes collection
- Create an endpoint that returns all the resumes that still need to be manually approved
- Create an endpoint to allow users to authenticate as an administrator/officer

Frontend
- Create a table component similar to what we currently have at the /demos endpoint where users with a sufficient permission level can click an approve button to add the resume to the production/final resumes collection
- Create a page where users can input a code to become authenticated as an admin/officer (Figure out a better method for this in the future, this should be fine for now)
 
TODO: 
- Have a deny button and have officers manually reach out to members to have them submit a corrected resume?
    - If we have time having a deny button that opens a text box somewhere for an officer to input a message that is then emailed to the member in question on why their resume entry got denied and the steps needed to correct it would be really cool and nice to have.

### PR DESCRIPTION
**Pull request by gabriel-flynn**
When new resume entries are added they now won't automatically show up in the production table/ResumeBook as they must go through an approval process first.

closes #17

### CODE REVIEW

**Comment by gabriel-flynn** [comment]
@davidagtz To test this one you'll have to add a environment variable in netlify called OFFICER_CODE (value can be whatever you want, just need to remember it so that you can verify yourself). It's used for the /officer/verify route to verify yourself as an officer and the code for that component/page is almost exactly the same as the code for the /verify route. You could also manually set officer: true in firebase if you want to do that too.

The manual approval table is located at the /officer endpoint. One thing we might want to consider in the future is being able to see everything in the resumes collection (allow for the ability to unapprove resumes that have been approved for a while). I decided to keep it simple for now and you can still approve and unapprove, its just that once you approve a resume and refresh the page you can't unapprove the ones that you just approved. (The manual approval table only contains resumes that were initially unapproved).

**Comment by davidagtz** [comment]
Of the following comments. two are urgent:

- The situation in which officer code is wrong is not handled
- We should probably put some protection for automated code putting or use a different system
- No method for unapproving resumes
- When approving resumes, I get the following error
```
Unable to retrieve resumes from the database
{ Error: 5 NOT_FOUND: No document to update: projects/resumebook-cd463/databases/(default)/documents/resumes/undefined
    at Object.callErrorFromStatus (src/functions/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (src/functions/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (src/functions/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (src/functions/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (src/functions/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (src/functions/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (src/functions/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.handleTrailers (src/functions/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:273:14)
    at ClientHttp2Stream.emit (events.js:198:13)
    at emit (internal/http2/core.js:265:8)
Caused by: Error
    at WriteBatch.commit (src/functions/node_modules/@google-cloud/firestore/build/src/write-batch.js:415:23)
    at DocumentReference.update (src/functions/node_modules/@google-cloud/firestore/build/src/reference.js:378:14)
    at app.post (src/functions/api.js:205:8)
    at Layer.handle [as handle_request] (src/functions/node_modules/express/lib/router/layer.js:95:5)
    at next (src/functions/node_modules/express/lib/router/route.js:137:13)
    at complete (src/functions/node_modules/passport/lib/middleware/authenticate.js:268:13)
    at src/functions/node_modules/passport/lib/middleware/authenticate.js:275:15
    at pass (src/functions/node_modules/passport/lib/authenticator.js:431:14)
    at Authenticator.transformAuthInfo (src/functions/node_modules/passport/lib/authenticator.js:453:5)
    at src/functions/node_modules/passport/lib/middleware/authenticate.js:272:22
  code: 5,
  details:
   'No document to update: projects/resumebook-cd463/databases/(default)/documents/resumes/undefined',
  metadata: Metadata { internalRepr: Map {}, options: {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }
```

**Review by davidagtz — COMMENTED** [review]
- Fix approve error
- Error handle for wrong officer code

**Review by davidagtz — APPROVED** [review]
The only feature I could think to add would be a filter button for approved/unapproved resumes but I don't know if you wanna make that another issue

So we can change this in a different branch, but I would like to show "hide" when the pdf is viewed

**Comment by gabriel-flynn** [comment]
@davidagtz That sounds like a really good idea! Can you make an issue for that and then we can assign that at the next meeting?

**Pull request merged**
