### PR TITLE
Aesthetic changes

### LINKED ISSUE #26: Add Favicon

### LINKED ISSUE #27: Fix Minimum GPA input width
- On Firefox the minimum input is not displaying as expected

### PR DESCRIPTION
**Pull request by davidagtz**
Several Changes:
- Made the favicon SHPE's logo
- Fixed Home button
- Made it "Remove" instead of "Remove from cart"
- Got rid of eslint error
- Fixed Bug of the Min GPA input in Firefox

### CODE REVIEW

**Review by gabriel-flynn — CHANGES_REQUESTED** [review]
It looks like there is an error on netlify when trying to build the react app, can you try installing/saving node-sass to our package.json and see if that fixes it? (npm install node-sass --save).  We might want to change the title to ResumeBook or something along those lines instead of having the title be SHPE UTD since this probably isn't going to be linked to/connected to our main website but we can revisit that later. Everything else looks really good! Haven't gotten a chance to run it locally yet but the screenshots you showed me were great

**Comment by davidagtz** [comment]
Do you mind sending a pic of your error? I don't get it, and sass-loader is in the node_modules from create-react-app/

**Comment by gabriel-flynn** [comment]
Log file is here: https://app.netlify.com/sites/angry-hugle-73e6e1/deploys/5f0bb0a0888c7500072c858d

I'm not sure if you have access to that but basically it's saying that it's failing to import/compile the sass file when building the react app. I found an article/tutorial on sass + create react app here and it mentions installing node-sass in order to use sass(there might be a way to do it with sass-loader but I haven't looked into that): 
https://create-react-app.dev/docs/adding-a-sass-stylesheet/

**Comment by davidagtz** [comment]
I changed the title to "ResumeBook" and added node-sass. Still works on my machine, so please test it.

**Comment by gabriel-flynn** [comment]
FilterPane firefox vs chrome

Right now the firefox Minimum GPA label is stacked and it looks like I didn't setup the grid correctly when I originally implemented that component.

Can you change the code starting at line 75 in the FilterPane component to be 
```
<Grid container>
  <FormControlLabel
     <!-- remove className="gpa-container" -->
     <!-- adding the line below is really important -->
     style={{ marginRight: '0px', justifyContent: 'start' }}
     keep other stuff here
     control={
       <Grid item xs={4}>
         <Input>
        </Grid>
     }
  />
</Grid>
```

That should make the input take up 4 columns and the justify-content css should fix some issues we were having with flexbox on firefox. I tested the change above and it worked for me so that should hopefully fix any formatting issues we were having on firefox. 

This implementation (unfortunately) eliminates the need to have the gpa-container class and FilterPane.sass file. Once the changes below have been implemented I'll go ahead and merge this PR, thanks David! The new favicon was definitely needed and the new home button  looks awesome!

Just to highlight the changes needed:

- Change line 75 to **`<Grid container>`**
- Remove FilterPane.sass and **`className="gpa-container"`**
- Add property **`style={{ marginRight: '0px', justifyContent: 'start' }}`** to the FormControlLabel component
- Wrap the Input component in  **`<Grid item xs={4}>`**
- Closing **`</Grid>`**

**Comment by gabriel-flynn** [comment]
Sorry, forgot to add that you adding node-sass as a dependency fixed the build issue!

**Comment by davidagtz** [comment]
All done!

**Review by gabriel-flynn — APPROVED** [review]

**Pull request merged**
